### ISSUE TITLE
Size of the repro is HUGE

### ISSUE THREAD

**Issue by hamogu** [alexbinks/tessilator#4]
When I cloned this locally, I found I needed to download > 400 MB and unpacked, it's 1.4 GB. The `tessilator/` directory itself is only a (reasonable) 13 MB. About 1GB is in `tesssim/` and 400 MB are in `.git` (objects in the git history that are not in the current version). I did not check, but likely other data files that got added and removed/changed later. 

What is the data in tesssim good for anyway? There is no README in that directory, it's not mentioned at all in the top-level README. 
It seems to be used in `tesssimulations.py` (but that uses the fits files, which are not part of the repro because they are explicitly excluded in the `.gitignore`) and in `tessilator.fix_noise_lc_sim` which has a note saying "I'm cancelling this procedure until we get new lightcurves" (whatever that means).

So, it seems that all this was added by accident?

**Comment by hamogu** [comment]
If my suspicion is correct, we can use ways to monkey with the git history (see e.g. the second answer here: https://stackoverflow.com/questions/2100907/how-can-i-remove-delete-a-large-file-from-the-commit-history-in-the-git-reposito ) but we definitely want to make a backup first. 
Rewriting history is a very bad thing because it screws over anyone who has cloned this repository already, but in a case like this it might be the only way to fix it. We'd have to manually talk to people who cloned it in the past (likely they are all your collaborators) an ask them to (1) make sure they don't keep any personal files to keep in their tessilator directory (2) `rm -rf` their local copy and (3) clone again.

**Comment by hamogu** [comment]
The same commit that added all the data files ([2fde6d9](https://github.com/alexbinks/tessilator/commit/2fde6d9f0ddb27c10b1530aad18cf36fe3a8e177)) also added a bunch of *pyc files in `__pycache__` that should never have been added. Any commit with > 8000 files added is a bit suspicious...

**Comment by alexbinks** [comment]
I think this is a fairly substantial job I need to sort out. At some point I must have inadvertently done something like "git add *" (or something similarly naïve) which has resulted in a large number of unwanted/unnecessary files. I *was* thinking about providing the tesssimulations.py and the associated files as a tool for others to use, but now I'm wary of it, mainly because of the huge file space, but also because it's a very niche way of doing things that is becoming difficult to explain.
If you think the only way to fix these commits is to go back and rewrite the history, then we can. FWIW I don't think anyone is using this software for their own purposes right now and we would be safe to clean things up this way.
